CREATE TABLE ANIMALS(
	ANIMAL_ID				INT		PRIMARY KEY		AUTO_INCREMENT,
	CENTER_IDX				INT,
	ANIMAL_TYPE				VARCHAR(20),
	ANIMAL_SORT				VARCHAR(20),
	ANIMAL_GENDER			VARCHAR(20),
	ANIMAL_NEUTER			VARCHAR(20),
	ANIMAL_INOCULATION	VARCHAR(20),
	ANIMAL_FEATURE			VARCHAR(500),
	ADOPTION_DATE			DATE,
	MEMBER_IDX				INT,
	IMG_1						VARCHAR(500),
	IMG_2						VARCHAR(500),
	IMG_3						VARCHAR(500),
	IMG_4						VARCHAR(500),
	IMG_5						VARCHAR(500),
	IMG_6						VARCHAR(500)
);

SELECT * FROM ANIMALS;

DROP TABLE ANIMALS;